### ISSUE TITLE
Git gud Learn to use linux

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [vizs/manjarno#3]
less crying would be great 
you clearly know nothing about linux
and to ever use reddit as a source of news is a disgrace 

Go back to Debian aka Baby Linux Arch doesnt need losers like you

**Comment by vizs** [comment]
I think you didn't actually look at the reddit link. If you did open it, you can see that it redirects to a manjaro page. If you really want some proof, I can link to archive.org page which shows manjaro website when it had an expired ssl certificate.

The whole point of this repo is to collect all the bad things about manjaro and help new linux users to use a better, non-broken distro that is not manjaro. Manjaro's only purpose is to serve as an example for "How to make a really shitty distro?"

**Comment by vizs** [comment]
Also, keeping the issue open to see you cry

**Comment by diamondburned** [comment]
Manjaro users once again was proven wrong with facts and logic.
