### ISSUE TITLE
Manjaro is a great way to get started on Linux

### ISSUE THREAD

**Issue by diamondburned** [vizs/manjarno#4]
Manjaro is actually a great way to started using Linux, as most of these problems are in the past, and the repository being held back actually offers stability.

Now that I got your fucking attention, why did you leave all the Discord servers?

**Comment by OwOAudrey** [comment]
i agree

**Comment by ym1234** [comment]
no u

**Comment by knuxfanwin8** [comment]
I'd just like to interject for a moment.  What you're referring to as Manjaro Linux,
is in fact, Arch Linux, or as I've recently taken to calling it, Broken Arch Linux.
Manjaro Linux is not its own distro, but rather another dumb modification
of a fully functioning Arch system made useful by the AUR capabilities and rolling release packages.

**Comment by vizs** [comment]
@diamondburned LMAO, I didn't actually see this issue. TBH, I think this would have gotten my attention

**Comment by vizs** [comment]
for anyone who's from the future:
firstly, hi!

i joined the server again because im gay as fuck and bored all the fucking time

**Comment by xgqt** [comment]
> for anyone who's from the future:
> firstly, hi!
> 
> i joined the server again because im gay as fuck and bored all the fucking time

Hello from the future.
Your comment made my day :D

**Comment by vizs** [comment]
I'm happy that it made your day :)

**Comment by binex-dsk** [comment]
> the repository being held back actually offers stability.

**Comment by vizs** [comment]
Truer words never said before!
