### ISSUE TITLE
help wanted: question re "bar" but you've disabled "issues"

### ISSUE THREAD

**Issue by jaimet** [vizs/manjarno#7]
Hi.

Apologies for contacting you through this repo, but I'd like to ask you a question regarding your [bar repo](https://github.com/vizs/bar) where you have disabled github "issues" (I want to ask you whether you'd consider accepting [this patch](https://github.com/shdown/bar/commit/eb0e9e79b9a35c3093f6e2e90d9fbd175a2305ef.patch) to fix the lemonbar bug explained [here](https://github.com/shdown/luastatus/tree/master/barlibs/lemonbar)).

If you don't want to talk about it, then please feel free to close this issue with no further comment and I will understand. If, however, you would consider the patch, then please let me know the best way for me to continue this conversation.

Thank you very much for continuing to maintain your bar fork - I appreciate your work.

Jaime

**Comment by vizs** [comment]
@jaimet pls check the bar repo
